use his;
TRUNCATE TABLE bottle_info;
TRUNCATE TABLE bottle_loc_cabinet;
TRUNCATE TABLE bottle_log;
TRUNCATE TABLE bottle_transaction;
TRUNCATE TABLE instock_log;
TRUNCATE TABLE medi_trans;
TRUNCATE TABLE medicine_loc_cabinet;
TRUNCATE TABLE medication;
TRUNCATE TABLE medication_detail;
TRUNCATE TABLE medicineequipment_base;
TRUNCATE TABLE menu;
